-- ═══════════════════════════════════════════════════
-- V11: Add Embedding Column to Memories Table
-- Phase 2: Semantic Memory
--
-- Stores vector embeddings for each memory.
-- Generated by Ollama nomic-embed-text model.
-- Dimension: 768 (nomic-embed-text output size)
--
-- SEMANTIC SEARCH FLOW:
-- 1. User asks: "What coding project am I working on?"
-- 2. Embed the question → [0.45, 0.12, 0.88, ...]
-- 3. Find memories with similar embedding vectors
-- 4. Returns: "User is building Jarvis AI Platform"
--    even though words don't match exactly
-- ═══════════════════════════════════════════════════

-- Add embedding column to memories table
-- vector(768) = 768-dimensional embedding
-- nomic-embed-text produces 768 dimensions
-- NULL allowed: memories without embeddings still work
ALTER TABLE memories
    ADD COLUMN embedding vector(768);

-- ── Phase 1: No index yet ─────────────────────────
-- For small datasets (< 1000 memories):
-- Exact search (no index) is fast enough.
-- Index will be added in a future migration
-- when semantic search is heavily used.

-- ── Future: HNSW index (Phase 2 Session 5+) ───────
-- HNSW = Hierarchical Navigable Small World
-- Approximate nearest neighbor search
-- ~99% accuracy, much faster for large datasets
-- Will be added via:
-- CREATE INDEX idx_memories_embedding_hnsw
--     ON memories
--     USING hnsw (embedding vector_cosine_ops)
--     WITH (m = 16, ef_construction = 64);

-- ── Helper function for similarity search ─────────
-- Returns memories ordered by semantic similarity
-- to a given query embedding vector
CREATE OR REPLACE FUNCTION search_memories_by_embedding(
    p_user_id UUID,
    p_embedding vector(768),
    p_limit INTEGER DEFAULT 5,
    p_min_similarity FLOAT DEFAULT 0.5
)
RETURNS TABLE (
    id              UUID,
    type            VARCHAR(20),
    content         TEXT,
    importance      DECIMAL(3,2),
    access_count    INTEGER,
    similarity      FLOAT,
    created_at      TIMESTAMPTZ
)
LANGUAGE SQL
STABLE
AS $$
SELECT
    m.id,
    m.type,
    m.content,
    m.importance,
    m.access_count,
    -- Cosine similarity: 1 = identical, 0 = unrelated
    1 - (m.embedding <=> p_embedding) AS similarity,
    m.created_at
FROM memories m
WHERE
    m.user_id = p_user_id
  AND m.embedding IS NOT NULL
  -- Only return memories above similarity threshold
  AND 1 - (m.embedding <=> p_embedding) >= p_min_similarity
ORDER BY
    -- Primary: semantic similarity
    m.embedding <=> p_embedding ASC,
        -- Secondary: importance score
        m.importance DESC
    LIMIT p_limit;
$$;

COMMENT ON FUNCTION search_memories_by_embedding IS
    'Finds semantically similar memories using cosine distance.
     Lower <=> distance = higher similarity.
     Returns top N memories above min_similarity threshold.
     Used by Jarvis to inject relevant context into prompts.';

COMMENT ON COLUMN memories.embedding IS
    'vector(768) embedding from Ollama nomic-embed-text.
     NULL = memory has no embedding yet.
     Populated asynchronously after memory is created.
     Used for semantic similarity search.';