package ai.jarvis.chat.message;

public enum MessageRole {

    USER,        // Message sent by the human user
    ASSISTANT,   // Message generated by the AI
    SYSTEM,      // System prompt (not shown to user)
    TOOL         // Tool call result (Phase 4)
}
